### ISSUE TITLE
does not exit after tests run

### ISSUE THREAD

**Issue by jperry** [dflynn15/gulp-jasmine-phantom#34]
When I run the task below with this plugin my tests pass but it never exists until I Ctrl-C it.  Any idea?

```
gulp.task('test-server', function () {
  return gulp.src('spec/server/**/*.js')
    .pipe(jasmine());
});
```

**Comment by dflynn15** [comment]
I need a little more than that :smile: is this currently implemented in a project I can look at? As it stands, that task should exit just fine. The code you pasted up doesn't give me much to go on.

**Comment by dflynn15** [comment]
This has been open for over a week and I still haven't gotten any information. I will reopen if you leave me more to go off of, but as it stands the plugin is working great for everyone else :+1:
