### ISSUE TITLE
Update Jasmine

### ISSUE THREAD

**Issue by matheusazzi** [dflynn15/gulp-jasmine-phantom#38]
This gulp task has an outdated version of Jasmine, can you update it to the stable Jasmine 2.3.x ?

**Comment by dflynn15** [comment]
I think what would be a better approach is to allow any of the main versions to be used through a flag. A lot of code bases will need to maintain a Jasmine version so that they don't have to rewrite a whole test suite, and it would be more future friendly to expose it as an option.
