### ISSUE TITLE
Cannot npm this plugin

### ISSUE THREAD

**Issue by donnrri** [dflynn15/gulp-jasmine-phantom#43]
npm install --save-dev gulp-jasmine-phantom

Errors thrown:

npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/dflynn15/minijasminenode) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (https://github.com/dflynn15/minijasminenode) undefined
npm ERR! git clone https://github.com/dflynn15/minijasminenode undefined
npm ERR! git clone https://github.com/dflynn15/minijasminenode undefined
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by dflynn15** [comment]
Is this still happening? I cannot currently reproduce this error.

**Comment by donnrri** [comment]
Yes , just checked it 
Thanks for any help with it.

**Comment by dflynn15** [comment]
Can you provide any other information? I cannot reproduce this on any of my machines nor any of my CI environments.

**Comment by donnrri** [comment]
Hi Daniel,

Thanks for your email.  I'm just running 'npm install --save-dev
gulp-jasmine-phantom' command from my terminal in my Webstorm IDE. The npm
manager is working for other installs that I make.

As I am the only person reporting this perhaps its  a weird one off. But
when I search npm for 'gulp-jasmine-phantom', there is none listed the only
suggested package is gulp-jasmine2-phantomjs.

Thanks for any assistance you can provide.

Regards
Dave

**Comment by dflynn15** [comment]
Are you using a private `npm`? Where exactly are you searching? I went searching for the package at `npmjs.com` and found it here:
![screenshot 2015-08-05 09 24 45](https://cloud.githubusercontent.com/assets/1205286/9086719/11a7c664-3b54-11e5-949a-70506927b0d7.png)

**Comment by donnrri** [comment]
Hello

Very odd. I attach a screenshot of my search at https://www.npmjs.com

I am totally at a loss to see why this is happening.

**Comment by dflynn15** [comment]
Your screenshot wasn't added. I do realize that it does not show up under the "suggested quick links" in the search bar, but if you submit the search it shows up.

**Comment by dflynn15** [comment]
As a sidenote, what version of `npm` are you running? It may not be up to date and could not have the feature that pulls in repositories from Github in the package.json

**Comment by donnrri** [comment]
Thanks for the mail. You're right gulp-jasmine-phantom there but doesn't
show on autocomplete

I'm using npm 1.4.28

Will look to update to see if the problem is solved

Many thanks for your time

**Comment by dflynn15** [comment]
I haven't heard back so I am going to assume that upgrading `npm` versions worked. If it did not feel free to re-open the issue.

**Comment by donnrri** [comment]
Hi

Sorry for not replying sooner. Thanks again for your time.
