### ISSUE TITLE
Jasmine with integration=true => ENOENT: Tests contained failures. Check logs for details.

### ISSUE THREAD

**Issue by Nasicus** [dflynn15/gulp-jasmine-phantom#44]
When I'm running the tests with `integration: true` I always get errors. Without the `integration` parameter it works.

Host system: Windows
PhantomJS: Not globally installed (only as a node module)

gulpfile.js:

	var gulp = require("gulp"),
		jasmine = require('gulp-jasmine-phantom');

	  gulp.task("runTests", function () {
		return gulp.src("./test.js")
			.pipe(jasmine({
			  integration: true
			}));
	  });

package.json:

	{
	  //...
	  "dependencies": {
		"gulp": "^3.8.11",
		"gulp-jasmine-phantom": "^1.3.3",
		"phantomjs": "^1.9.17"
	  }
	}

If I run my gulp task I get the following:

	[15:47:01] Running Jasmine with PhantomJS
	[15:47:01] gulp-jasmine-phantom: Global Phantom undefined, trying to execute from node_modules/phantomjs
	[15:47:01] 'runTests' errored after 34 ms
	[15:47:01] Error in plugin 'gulp-jasmine-phantomjs'
	Message:
		ENOENT: Tests contained failures. Check logs for details.
	Process terminated with code 1.

After some investigation (putting some log in the `index.js` files, namely within the callback function of `execFile` I also got the following output for the `error` parameter:

	{"code":"ENOENT","errno":"ENOENT","syscall":"spawn"}

I have no idea what causes this error and how to fix it - hope someone can help.

**Comment by Vitaliy-Yarovuy** [comment]
I have simular situation, and fix that  just replace 
https://github.com/dflynn15/gulp-jasmine-phantom/blob/master/index.js#L105
to: "/node_modules/phantomjs/lib/phantom/phantomjs"

**Comment by Nasicus** [comment]
This is indeed also what I could observe - however since I do not really have node.js knowledge I didn't think that this is the correct solution however if it is, then you should maybe make a pull request for this fix.

**Comment by dflynn15** [comment]
Where are you running `gulp` from? The `process.cwd()` grabs the current working directory (where you executed `gulp taskname`) and looks inside that directories `node_modules` folder.

`/node_modules/phantomjs/lib/phantom/phantomjs` is an ambiguous path that could result in other path problems outside of Windows.

**Comment by Nasicus** [comment]
Hey @dflynn15 I run the gulp task (and also node itself) directly from VS 2015. Also I did check if the path `process.cwd() + '/node_modules/phantomjs/bin/phantomjs'` is correct --> it is (even though `/` and `\ ` are mixed, it may be a good idea to use `path.join` there). The path is in the end something like this `c:\git\myVSSolution\myVSProject/node_modules/phantomjs/lib/phantom/phantomjs`.

What do you mean with ambiguous ?  As far as I can see in the `bin` directory is a `node.js` file (`phantom.js`)  while in the `lib`directory is a `exe`. 

If you don't have (access to) VS 2015 - I can gladly post the "folder structure" / "setup" which happens when you use VS 2015 if this would help you.

PS: I also noticed that `hasGlobalPhantom()` always returns false for me even if I set the `PATH` variable (I can verify that it is correct within a cmd or if I start node.js directly). As far as I could see there occurs always an exception (when trying to do `exec` in the method and this is why false is returned). However this is a different issue. Just wanted to give notice :)

**Comment by dflynn15** [comment]
Ambiguous means it could be looking at the run time current directory, the system root directory, or the root of the gulp plugin. 

What version of node are you on?

**Comment by Nasicus** [comment]
I think you misunderstood us. We were not talking about omitting the `process.cwd()`, but of replacing `process.cwd() + '/node_modules/phantomjs/bin/phantomjs'` with `process.cwd() + '/node_modules/phantomjs/lib/phantom/phantomjs'`.

The node version is (printed out with `process.version`): v0.10.31

**Comment by dflynn15** [comment]
For starters you will need to upgrade to 0.12. It is noted in the readme. Either that or have Phantom installed globally.

**Comment by dflynn15** [comment]
The module needs 0.12 because of execSync so that it can correctly determine if you have phantom installed or not.

**Comment by Nasicus** [comment]
Sorry I'm pretty sure I printed out the wrong version. I didn't know how to get the version so i printed the `process.version` from inside your `index.js`file.... However some more researching resulted in that there is a node console within VS 2015 and if I print the version there I get `v0.12.5`.

**Comment by Vitaliy-Yarovuy** [comment]
> Are you sure that this "fix" will also work on linux (and not introduce a bug)?
you can look in my branch that i use it just for windows operation system.

https://github.com/Vitaliy-Yarovuy/gulp-jasmine-phantom/blob/master/index.js#L106
ps. in my case i need support windows first.

**Comment by Nasicus** [comment]
@dflynn15 @Vitaliy-Yarovuy 
Indeed using the newest node.js version fixes this issue! I apologize for not seeing this myself, I somehow assumed that VS 2015 would use a newer version.

For all who want to fix this (until MS decides to upgrade the node version used by VS):
0. Install Node.js
0. Go to "Tools -> Options -> Projects and Solutions -> External Web Tools" and add a new location : `C:\Program Files\nodejs\`, move this new location above of `$(DevEnvDir)\Extensions\Microsoft\Web Tools\External`

Note: Alternatively you can also just install node.js and then move the `$(PATH)` above `$(DevEnvDir)\Extensions\Microsoft\Web Tools\External`

**Comment by Nasicus** [comment]
Sorry but I have to reopen this issue!

The solution above is only a partial solution.
What I realized is that the script only works if `hasGlobalPhantom()` returns true and the `phantomjs.cmd` can be used.

However if the `phantomjs.cmd` 's directory is NOT in the path and the other case occurs:

	  } else {
		gutil.log(gutil.colors.yellow('gulp-jasmine-phantom: Global Phantom undefined, trying to execute from node_modules/phantomjs'));
		execPhantom(process.cwd() + '/node_modules/phantomjs/bin/phantomjs', childArguments, onComplete);
	  }

It will never work on windows and the error message from the first post will be returned.
I'm on the newest node version.
Is it maybe possible, that on windows `execPhantom` respectively `execFile` cannot execute JavaScript files (because the file which it's trying to execute `/node_modules/phantomjs/bin/phantomjs` is a JS file)?

**Comment by dflynn15** [comment]
Please output what the `process.cwd()` is when you run your `gulp taskname`.

**Comment by Nasicus** [comment]
it's `0.12.7`

**Comment by dflynn15** [comment]
If you are truly getting `0.12.7` when you log out `process.cwd()` while running `gulp youtaskhere` than I am bewildered. 

Please see: https://nodejs.org/api/process.html#process_process_cwd

**Comment by Nasicus** [comment]
Sorry I misread...I thought ou wrote `process.version`. The output is `c:\Myproject\Core.Client`.

I can assure you that this path and also the path which points to the phantomjs is correct.

**Comment by dflynn15** [comment]
So you have the `node_modules` directory along the path `c:\Myproject\Core.Client\node_modules`?

**Comment by Nasicus** [comment]
This will not work since the `phantomjs`  is a JS file.Or are you talking about executing it with node? (Haven't tried that yet I think (expect with `execFile` and then it won't work)).

However with either `c:\Myproject\Core.Client\node_modules\.bin\phantomjs.cmd` or `c:\Myproject\Core.Client\node_modules\phantomjs\lib\phantom\phantomjs.exe` it does work.

**Comment by Nasicus** [comment]
I'm back at a computer and could try to execute it with node:

When I execute the command

`node c:\Myproject\Core.Client\node_modules\phantomjs\bin\phantomjs`

it works.

**Comment by dflynn15** [comment]
I updated the module to `2.0` in order to account for the breaking dependency for Node 0.12.x . 

Also, is there a `.exe` or `.cmd` file in the directory `node_modules\phantomjs\bin`?

**Comment by Nasicus** [comment]
I updated to the new version but this doesn't help.

And no - the `node_modules\phantomjs\bin` folder only contains the file `phantomjs` (which is a JavaScript file).

The `phantomjs.exe` can be found in `node_modules\phantomjs\lib\phantom` .
The `phantomjs.cmd` can be found in `node_modules\.bin`.

**Comment by dflynn15** [comment]
Sorry for the long response, I just updated to `2.0.1` that includes the `phantomjs.cmd` that you referenced in the `node_modules/.bin`

**Comment by Nasicus** [comment]
Hi - no problem!

Just tested it and this fixes the issue for me.

Thanks for your effort!
