### ISSUE TITLE
Update to Minijasminenode 23

### ISSUE THREAD

**Issue by mjancarik** [dflynn15/gulp-jasmine-phantom#45]
Hi,

It could be possible update which use jasmine version 2.3.

**Comment by dflynn15** [comment]
If you are asking me to update https://github.com/juliemr/minijasminenode I think it's best to ask Julie to do it there. Otherwise I may not be fully understanding what your question is.

**Comment by mjancarik** [comment]
I use your npm package gulp-jasmine-phantom and you have dependency "minijasminenode2": "dflynn15/minijasminenode" in package.json. It's your repo, so I ask you it is posssible to update it so that I could run test with jasmine 2.3 version on node. Now minijasminenode2 run test only with jasmine 2.0 version. Current version of gulp-jasmine-phantom package allow me to run test with jasmine 2.3 version only on phantom.

**Comment by mjancarik** [comment]
Maybe you can use this repo https://github.com/theogravity/minijasminenode23 for it.

**Comment by dflynn15** [comment]
I don't want to maintain another version of minijasminenode2 that moves even farther away from the existing project. 

That feature should probably be request to Julie in her repo. I am staying in sync with her master branch. 

If you want to do the work I can always make a PR under my forked version of minijasminenode.

**Comment by dflynn15** [comment]
The changes I made to minijasminenode would have to be changed in the module you suggested. If the maintainer allows for multiple custom reporters I can switch over.

**Comment by mjancarik** [comment]
It's not possible to do it with minijasminenode.addReporter function?

**Comment by dflynn15** [comment]
It is a bit unique. Take a look at the PR I have out for the current minijasminenode2 for the diff.

**Comment by mjancarik** [comment]
Please write more information on https://github.com/theogravity/minijasminenode23/issues/2

**Comment by theogravity** [comment]
Saw this via a search, @dflynn15 's changes have been merged in a while back.

**Comment by dflynn15** [comment]
So, in the next major release (`v3.0`) I am just going to stop using `minijasminenode` and track with Jasmine's node runner. This won't give you `v2.3` explicitly, but it will stay in step with Jasmine (proper) and give you the APIs you may want for your tests.

Feel free to grab `3.0.0-beta` and test it out. It'll probably be merged in the next few days as I continue to use it on my projects at work to try and stress test it.

**Comment by dflynn15** [comment]
This project no longer is using `minijasminenode`. [Check out the release PR for updates.](https://github.com/dflynn15/gulp-jasmine-phantom/pull/56)
