### ISSUE TITLE
How to set the text encoding?

### ISSUE THREAD

**Issue by cweb** [dflynn15/gulp-jasmine-phantom#47]
My tests with Unicode are failing because I'm not sure how to set the text encoding for phantomjs to UTF-8 when using 'integration: true'.  For example, consider U+0100 LATIN CAPITAL LETTER A WITH MACRON:

expect("Ā".length === 1).toBe(true);

But instead of length being 1, it's 2, because including 'console.log(document.charset)' shows that the tests are running with the ISO-8859-1 encoding.

**Comment by dflynn15** [comment]
This looks to be fixed through: https://github.com/dflynn15/gulp-jasmine-phantom/pull/48

**Comment by dflynn15** [comment]
I am assuming this was fixed in #48. If this is still a problem feel free to re-open or submit any patches you may have come up with since August.
