### ISSUE TITLE
Can you please provide one example of test that is using phantomjs

### ISSUE THREAD

**Issue by mato75** [dflynn15/gulp-jasmine-phantom#51]

**Comment by dflynn15** [comment]
You can see how to run integration tests here in the example file (https://github.com/dflynn15/gulp-jasmine-phantom/blob/master/example/gulpfile.js#L42-L48) and in the README (https://github.com/dflynn15/gulp-jasmine-phantom/blob/master/example/gulpfile.js#L42-L48).

This repo liberally uses the term "integration test" to correlate running Phantom to execute tests. You can run any set of tests through Phantom passing the option `integration: true`.
