### ISSUE TITLE
Broken with npm v3

### ISSUE THREAD

**Issue by ChALkeR** [dflynn15/gulp-jasmine-phantom#55]
See https://github.com/juliemr/minijasminenode/issues/30, the same affects your fork.

**Comment by dflynn15** [comment]
As `minijasminenode` is no longer being maintained I am actively developing a version that no longer depends on it. If you are willing, please check out the `3.0.0-beta` branch. That branch works perfectly with `npm 3` :+1:

**Comment by ChALkeR** [comment]
@dflynn15 Could you please publish 3.0.0-beta1 to npm?

If you add a tag to it (`next`, `beta`, or something like that, anything but `latest`) — it would not be installed by default when one types `npm install gulp-jasmine-phantom`. People usually use `next` (it's used for `koa` and `npm`, for example): `npm publish --tag next`. 

See https://docs.npmjs.com/getting-started/using-tags#publishing-with-tags.

**Comment by dflynn15** [comment]
I have gone ahead and published `3.0.0-rc1` as the first release candidate. `3.0.0-beta` was truly beta so I hadn't published it on account of the likely churn as I developed. It should be up on `npm` now :+1:

**Comment by ChALkeR** [comment]
Thanks!
