### ISSUE TITLE
Can not run tests via plugin gulp-jasmine-phantom, Windows 7, x64

### ISSUE THREAD

**Issue by alexkonkin** [dflynn15/gulp-jasmine-phantom#60]
Steps to reproduce:
- download a test repository with as simple test as it could be:
  https://github.com/alexkonkin/gulp-jasmine-phantom_bug.git
- install required plugins:
  npm install gulp
  npm install gulp-jasmine-phantom
  npm install phantomjs (or place phantomjs.exe binary to Windows/System_32 folder)
- run tests by executing the command
  gulp tests

Expected behavior:
- tests task that represents an execution of single test that engages 
  the utilization of this plugin should be passed

Actual result:
- the test is failed with the error:
  [10:24:26] Running Jasmine with PhantomJS

events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: ENOENT: Tests contained failures. Check logs for details.

Please also refer to the screenshot below:
http://screencast.com/t/D7GGTFJ3qwC

Other info:
Another plugin 
(https://github.com/sandermak/gulp-jasmine2-phantomjs)
is also unable to run the test. Has something changed in phantomjs.exe binary?

Jasmine2 can execute this test on its own:
http://screencast.com/t/Fn5kmjbypv

**Comment by alexkonkin** [comment]
Environment:
Windows 7 Enterprise, x64
Nodejs: 4.4.0

**Comment by dflynn15** [comment]
Can you add the Phantom version as well?

**Comment by dflynn15** [comment]
Actually, I'm closing this in favor of the issue history of #53. All of this information is there as well as multiple other people that can be pinged and perhaps help out.

**Comment by alexkonkin** [comment]
This bug report is related to the recent version of phanotmjs - 2.1
and the one that is installed via npm (1.9.8)

**Comment by alexkonkin** [comment]
Hello,

Sorry for the delay with my response.

Phantom version is 2.0, the recent version of Phantom that can be
downloaded from
the vendor's site.

Please let me know if you have any questions.

2016-03-21 19:40 GMT+02:00 Daniel Flynn <notifications@github.com>:
