### ISSUE TITLE
Plugin doesn't seem to exit properly with failed unit tests

### ISSUE THREAD

**Issue by jasonenglish** [dflynn15/gulp-jasmine-phantom#61]
Currently using Codeship to run unit and integration tests. Integration tests (with abortOnFail: true) works just fine, but when a failing unit test happens, it doesn't seem to exit with the correct status code.

Is there a way to get around this? Thanks for the help.

"gulp-jasmine-phantom": "^3.0.0"

```js
function unitTest() {
  return gulp.src(['spec/unit/**/*.js'])
    .pipe($.jasminePhantom({
      "jasmineVersion": "2.0",
      "includeStackTrace": true
    });
}
```

**Comment by dflynn15** [comment]
More than likely, however as the README notes:
> Currently built with integration mode only
> Exits Gulp with an status of 1 that will halt any further Gulp tasks.

Adding the option to unit tests is a feature down the road, but not as high priority as the Windows issues that currently exist. Feel free to make a PR though!

**Comment by jasonenglish** [comment]
Sorry forgot to update this, but I did find a solution if someone is trying to get around this.

Looking through the lib I noticed that all options are passed to [lib/terminal-reporter.js](https://github.com/dflynn15/gulp-jasmine-phantom/blob/05a9b6d6d2f02ac92e5ff044030b7e5b51710b1b/lib/terminal-reporter.js) in [index.js](https://github.com/dflynn15/gulp-jasmine-phantom/blob/05a9b6d6d2f02ac92e5ff044030b7e5b51710b1b/index.js#L257), the [lib/terminal-reporter.js](https://github.com/dflynn15/gulp-jasmine-phantom/blob/05a9b6d6d2f02ac92e5ff044030b7e5b51710b1b/lib/terminal-reporter.js) can accept a `done` [callback](https://github.com/dflynn15/gulp-jasmine-phantom/blob/05a9b6d6d2f02ac92e5ff044030b7e5b51710b1b/lib/terminal-reporter.js#L9) through options which is passed a `success {boolean}` argument, `false` being that there were failing tests. This worked perfectly in my case. 

Here's the solution using the previous example:

```js
function unitTest() {
  return gulp.src(['spec/unit/**/*.js'])
    .pipe($.jasminePhantom({
      jasmineVersion: "2.0",
      includeStackTrace: true,
      done: function(success) {
        if (!success) {
          process.exit(1);
        }
      }
    });
}
```

It might be helpful to note that the options get passed to [lib/terminal-reporter.js](https://github.com/dflynn15/gulp-jasmine-phantom/blob/05a9b6d6d2f02ac92e5ff044030b7e5b51710b1b/lib/terminal-reporter.js) in the README, allowing people to see what other options they could use. I'll create a PR hopefully this afternoon adding this
